name: money_mate
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.9.2
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get_it: ^8.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  velocity_x: ^4.3.1
  dio: ^5.9.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  retrofit: ^4.7.3
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  go_router: ^16.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  retrofit_generator: ^10.0.6
  json_serializable: ^6.11.1
  
flutter:
  uses-material-design: true
